spring:
    application:
        name: multiple-consumer-kafka

kafka:
    address: localhost:9092
message:
    topic:
        name: multiple-consumer-topic
greeting:
    topic:
        name: greeting
filtered:
    topic:
        name: filtered
partitioned:
    topic:
        name: partitioned
